<?php
// echo $_SERVER['REQUEST_URI']." ";
$head = "";
if (($_SERVER['HTTP_HOST'] == 'localhost')) {
    $head = "/indiastock";
}
$request = parse_url($_SERVER['REQUEST_URI']);
switch ($request['path']) {
    case "$head/index":
        require __DIR__ . '/main/index.php';
        break;
    case "$head/":
        require __DIR__ . '/main/index.php';
        break;
    case "$head";
        require __DIR__ . '/main/index.php';
        break;
    case "$head/administrator";
        require __DIR__ . '/main/admin.php';
        break;
    case "$head/about";
        require __DIR__ . '/main/about.php';
        break;
    case "$head/login";
        require __DIR__ . '/main/login.php';
        break;
    case "$head/adminlogin";
        require __DIR__ . '/main/adminlogin.php';
        break;
    case "$head/checkadminlogin";
        require __DIR__ . '/main/checkadminlogin.php';
        break;
    case "$head/viewrole";
        require __DIR__ . '/main/viewrole.php';
        break;
    case "$head/insertuserdirect";
        require __DIR__ . '/main/insertuserdirect.php';
        break;
    case "$head/edituser";
        require __DIR__ . '/main/edituser.php';
        break;
    case "$head/updateuser";
        require __DIR__ . '/main/updateuser.php';
        break;
    case "$head/deleteuser";
        require __DIR__ . '/main/deleteuser.php';
        break;
    case "$head/dashboard";
        require __DIR__ . '/main/dashboard.php';
        break;
    case "$head/userlogindetails";
        require __DIR__ . '/main/userlogindetails.php';
        break;
    case "$head/addinvestmentamount";
        require __DIR__ . '/main/addinvestmentamount.php';
        break;
    case "$head/insertinvestmentamount";
        require __DIR__ . '/main/insertinvestmentamount.php';
        break;
    case "$head/viewfundhistory";
        require __DIR__ . '/main/viewfundhistory.php';
        break;
    case "$head/test";
        require __DIR__ . '/main/test.php';
        break;
    case "$head/editrole";
        require __DIR__ . '/main/editrole.php';
        break;
    case "$head/updaterole";
        require __DIR__ . '/main/updaterole.php';
        break;
    case "$head/addrole";
        require __DIR__ . '/main/addrole.php';
        break;
    case "$head/insertrole";
        require __DIR__ . '/main/insertrole.php';
        break;
    case "$head/deleterole";
        require __DIR__ . '/main/deleterole.php';
        break;
    case "$head/permission";
        require __DIR__ . '/main/permission.php';
        break;
    case "$head/addpermission";
        require __DIR__ . '/main/addpermission.php';
        break;
    case "$head/insertpermission";
        require __DIR__ . '/main/insertpermission.php';
        break;
    case "$head/editpermission";
        require __DIR__ . '/main/editpermission.php';
        break;
    case "$head/updatepermission";
        require __DIR__ . '/main/updatepermission.php';
        break;
    case "$head/deletepermission";
        require __DIR__ . '/main/deletepermission.php';
        break;
    case "$head/checklogin";
        require __DIR__ . '/main/checklogin.php';
        break;
    case "$head/transaction";
        require __DIR__ . '/main/viewtransaction.php';
        break;
    case "$head/todaytransaction";
        require __DIR__ . '/main/viewtodaytransaction.php';
        break;
    case "$head/users";
        require __DIR__ . '/main/viewusers.php';
        break;
    case "$head/register";
        require __DIR__ . '/main/addusers.php';
        break;
    case "$head/insertuser";
        require __DIR__ . '/main/insertuser.php';
        break;
    case "$head/adduser";
        require __DIR__ . '/main/adduser.php';
        break;
    case "$head/pendingapproval";
        require __DIR__ . '/main/pendingapproval.php';
        break;
    case "$head/viewusermodal";
        require __DIR__ . '/main/viewusermodal.php';
        break;
    case "$head/approveuser";
        require __DIR__ . '/main/approveuser.php';
        break;
    case "$head/composemail";
        require __DIR__ . '/main/composemail.php';
        break;
    case "$head/insertmail";
        require __DIR__ . '/main/insertmail.php';
        break;
    case "$head/viewinbox";
        require __DIR__ . '/main/viewinbox.php';
        break;
    case "$head/viewmaildetail";
        require __DIR__ . '/main/viewmaildetail.php';
        break;
    case "$head/sentmails";
        require __DIR__ . '/main/sentmails.php';
        break;
    case "$head/insertmessage";
        require __DIR__ . '/main/insertmessage.php';
        break;
    case "$head/employeelist";
        require __DIR__ . '/main/employeelist.php';
        break;
    case "$head/addemployee";
        require __DIR__ . '/main/addemployee.php';
        break;
    case "$head/insertemployee";
        require __DIR__ . '/main/insertemployee.php';
        break;
    case "$head/editemployee";
        require __DIR__ . '/main/editemployee.php';
        break;
    case "$head/updatemployee";
        require __DIR__ . '/main/updatemployee.php';
        break;
    case "$head/employeeclient";
        require __DIR__ . '/main/employeeclient.php';
        break;
    case "$head/allinvestment";
        require __DIR__ . '/main/allinvestment.php';
        break;
    case "$head/pendinginvestment";
        require __DIR__ . '/main/pendinginvestment.php';
        break;
    case "$head/approvedinvestment";
        require __DIR__ . '/main/approvedinvestment.php';
        break;
    case "$head/disapprovedinvestment";
        require __DIR__ . '/main/disapprovedinvestment.php';
        break;
    case "$head/withdrawalrequest";
        require __DIR__ . '/main/withdrawalrequest.php';
        break;
    case "$head/todaytransactions";
        require __DIR__ . '/main/todaytransactions.php';
        break;
    case "$head/alltransactions";
        require __DIR__ . '/main/alltransactions.php';
        break;
    case "$head/settings";
        require __DIR__ . '/main/settings.php';
        break;
    case "$head/insertpersonalaccount";
        require __DIR__ . '/main/insertpersonalaccount.php';
        break;
    case "$head/logout";
        require __DIR__ . '/main/logout.php';
        break;
    default:
        http_response_code(404);
        require __DIR__ . '/main/404.php';
        # code...
        break;
}
