<?php
// echo $_SERVER['REQUEST_URI']." ";

$request = parse_url($_SERVER['REQUEST_URI']);
switch ($request['path']) {
    case '/indiastock/index':
        require __DIR__ . '/main/index.php';
        break;
    case '/indiastock/':
        require __DIR__ . '/main/index.php';
        break;
    case "/indiastock";
        require __DIR__ . '/main/index.php';
        break;
    case "/indiastock/administrator";
        require __DIR__ . '/main/admin.php';
        break;
    case "/indiastock/about";
        require __DIR__ . '/main/about.php';
        break;
    case "/indiastock/login";
        require __DIR__ . '/main/login.php';
        break;
    case "/indiastock/adminlogin";
        require __DIR__ . '/main/adminlogin.php';
        break;
    case "/indiastock/checkadminlogin";
        require __DIR__ . '/main/checkadminlogin.php';
        break;
    case "/indiastock/viewrole";
        require __DIR__ . '/main/viewrole.php';
        break;
    case "/indiastock/insertuserdirect";
        require __DIR__ . '/main/insertuserdirect.php';
        break;
    case "/indiastock/edituser";
        require __DIR__ . '/main/edituser.php';
        break;
    case "/indiastock/updateuser";
        require __DIR__ . '/main/updateuser.php';
        break;
    case "/indiastock/deleteuser";
        require __DIR__ . '/main/deleteuser.php';
        break;
    case "/indiastock/userprofile";
        require __DIR__ . '/main/userprofile.php';
        break;
    case "/indiastock/userlogindetails";
        require __DIR__ . '/main/userlogindetails.php';
        break;
    case "/indiastock/addinvestmentamount";
        require __DIR__ . '/main/addinvestmentamount.php';
        break;
    case "/indiastock/insertinvestmentamount";
        require __DIR__ . '/main/insertinvestmentamount.php';
        break;
    case "/indiastock/viewfundhistory";
        require __DIR__ . '/main/viewfundhistory.php';
        break;
    case "/indiastock/editrole";
        require __DIR__ . '/main/editrole.php';
        break;
    case "/indiastock/updaterole";
        require __DIR__ . '/main/updaterole.php';
        break;
    case "/indiastock/addrole";
        require __DIR__ . '/main/addrole.php';
        break;
    case "/indiastock/insertrole";
        require __DIR__ . '/main/insertrole.php';
        break;
    case "/indiastock/deleterole";
        require __DIR__ . '/main/deleterole.php';
        break;
    case "/indiastock/permission";
        require __DIR__ . '/main/permission.php';
        break;
    case "/indiastock/addpermission";
        require __DIR__ . '/main/addpermission.php';
        break;
    case "/indiastock/insertpermission";
        require __DIR__ . '/main/insertpermission.php';
        break;
    case "/indiastock/editpermission";
        require __DIR__ . '/main/editpermission.php';
        break;
    case "/indiastock/updatepermission";
        require __DIR__ . '/main/updatepermission.php';
        break;
    case "/indiastock/deletepermission";
        require __DIR__ . '/main/deletepermission.php';
        break;
    case "/indiastock/checklogin";
        require __DIR__ . '/main/checklogin.php';
        break;
    case "/indiastock/transaction";
        require __DIR__ . '/main/viewtransaction.php';
        break;
    case "/indiastock/todaytransaction";
        require __DIR__ . '/main/viewtodaytransaction.php';
        break;
    case "/indiastock/users";
        require __DIR__ . '/main/viewusers.php';
        break;
    case "/indiastock/register";
        require __DIR__ . '/main/addusers.php';
        break;
    case "/indiastock/insertuser";
        require __DIR__ . '/main/insertuser.php';
        break;
    case "/indiastock/adduser";
        require __DIR__ . '/main/adduser.php';
        break;
    case "/indiastock/logout";
        require __DIR__ . '/main/logout.php';
        break;
    default:
        http_response_code(404);
        require __DIR__ . '/main/404.php';
        # code...
        break;
}
